#####################################################
# wheel odometry node parameters
#####################################################

wheel_odometry_node:
  ros__parameters:

    # input
    motor_state_topic: "/motor_state"

    # output
    odom_topic: "/wheel/odometry"

    # tf
    odom_frame: "odom"
    base_frame: "base_link"

    # robot_localizationを使うならfalse推奨
    publish_tf: false

odom_to_path_node:
  ros__parameters:
    odom_topic: "/wheel/odometry"
    path_topic: "/wheel/path"
    max_path_length: 1000