#####################################################
# 車体ジオメトリ・駆動系定数
#
# 各ノード共通:
#   - pm_vehicle_interface
#   - pm_localization
#   - simulator
#   - planner
#####################################################

/**:
  ros__parameters:

    #################################################
    # vehicle geometry
    #################################################

    # タイヤ半径 [m]
    wheel_radius: 0.10

    # 左右タイヤ接地点間距離 [m]
    tread_width: 0.36

    #################################################
    # drivetrain
    #################################################

    # gear_ratio =
    #   motor_turns / wheel_turns
    #
    # 例:
    #   モータ10回転でタイヤ1回転
    #     -> gear_ratio = 10.0
    #
    gear_ratio: 10.0

    # 最大ホイール回転数 [rps]
    #
    # wheel軸基準
    #
    max_whl_rps: 4.0
